# -*- coding: utf-8 -*-
"""OCR code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ORr5YdibODjl70nbep9tLvtkCt4EfA0O
"""

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║   OCR DOCUMENT PROCESSING & DATA EXTRACTION SYSTEM                         ║
# ║   Industry Project — Google Colab Notebook                                 ║
# ║   Dataset: Tobacco3482 from Kaggle (real scanned corporate documents)       ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# HOW TO USE:
#   1. Open Google Colab → File → Upload notebook OR paste cells one by one
#   2. Runtime → Change runtime type → GPU (optional but faster)
#   3. Run cells from top to bottom IN ORDER
#   4. The dataset is downloaded automatically from Kaggle inside Cell 2
#
# ──────────────────────────────────────────────────────────────────────────────


# ██████████████████████████████████████████████████████████████████████████████
# CELL 1 ── Install all dependencies
# ██████████████████████████████████████████████████████████████████████████████

!apt-get install -y tesseract-ocr tesseract-ocr-eng libgl1 poppler-utils -q
!pip install -q pytesseract opencv-python-headless pillow scikit-learn \
               pandas matplotlib seaborn kaggle pdf2image tqdm reportlab
print("✅ All packages installed!")



# ██████████████████████████████████████████████████████████████████████████████
# CELL 2 ── Download Tobacco3482 Dataset from Kaggle
# ██████████████████████████████████████████████████████████████████████████████

# ── OPTION A: Upload your kaggle.json API key (recommended) ──────────────────
# 1. Go to https://www.kaggle.com → Account → Create API Token
# 2. Upload the downloaded kaggle.json when prompted below

from google.colab import files
uploaded = files.upload()          # upload kaggle.json

import os, shutil
os.makedirs("/root/.kaggle", exist_ok=True)
shutil.move("kaggle.json", "/root/.kaggle/kaggle.json")
os.chmod("/root/.kaggle/kaggle.json", 0o600)

# ── Download Tobacco3482 dataset ──────────────────────────────────────────────
# Dataset: 3482 grayscale scanned corporate document images across 10 classes
# Classes: letter, email, resume, scientific, note, news, memo,
#          advertisement, form, report
# Kaggle URL: https://www.kaggle.com/datasets/patrickaudriaz/tobacco3482jpg

!kaggle datasets download -d patrickaudriaz/tobacco3482jpg -p /content/ --unzip -q
print("✅ Tobacco3482 dataset downloaded!")
!ls /content/Tobacco3482-jpg/ | head -15

# ── OPTION B: If Kaggle API doesn't work, run this instead ───────────────────
# !pip install gdown -q
# import gdown
# gdown.download_folder(
#     "https://drive.google.com/drive/folders/1Ig22UbMDfBNNAWxpsSnm2dN7oUXa1hDR",
#     quiet=False, output="/content/Tobacco3482-jpg"
# )



# ██████████████████████████████████████████████████████████████████████████████
# CELL 3 ── Imports & Project Setup
# ██████████████████████████████████████████████████████████████████████████████

import os, re, json, random, shutil, warnings, pickle, time
from pathlib import Path
from collections import Counter

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from tqdm import tqdm

from PIL import Image, ImageDraw, ImageFont, ImageEnhance
import cv2
import pytesseract

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import (
    train_test_split, StratifiedKFold, cross_val_score
)
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    classification_report, confusion_matrix
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder

warnings.filterwarnings("ignore")

# ── Project directory structure ───────────────────────────────────────────────
ROOT = Path("ocr_project")
DIRS = {
    "processed": ROOT / "dataset" / "processed",
    "models":    ROOT / "models",
    "outputs":   ROOT / "outputs",
    "logs":      ROOT / "logs",
}
for d in DIRS.values():
    d.mkdir(parents=True, exist_ok=True)

# ── Tobacco3482 class mapping ─────────────────────────────────────────────────
# The dataset has 10 classes.  We keep all 10 by default, but you can
# restrict to a subset by editing KEEP_CLASSES below.
KEEP_CLASSES = None        # None = use all classes found in the folder
# KEEP_CLASSES = ["letter", "email", "memo", "report", "form"]  # optional subset

# ── Dataset root (adjust if your path differs) ────────────────────────────────
DATASET_ROOT = Path("/content/Tobacco3482-jpg")

print("✅ Setup complete.")
print(f"   Dataset root : {DATASET_ROOT}")
print(f"   Project root : {ROOT}")


# ██████████████████████████████████████████████████████████████████████████████
# CELL 4 ── Explore & Verify Dataset
# ██████████████████████████████████████████████████████████████████████████████

def explore_dataset(dataset_root: Path, keep_classes=None):
    """
    Walk the Tobacco3482-jpg folder structure.
    Expected layout:
        Tobacco3482-jpg/
            letter/
                img001.jpg  img002.jpg …
            email/
                …
    Returns a DataFrame with columns: [path, label]
    """
    records = []
    for cls_dir in sorted(dataset_root.iterdir()):
        if not cls_dir.is_dir():
            continue
        label = cls_dir.name.lower()
        if keep_classes and label not in keep_classes:
            continue
        for img_file in cls_dir.glob("*.jpg"):
            records.append({"path": str(img_file), "label": label})
        for img_file in cls_dir.glob("*.png"):
            records.append({"path": str(img_file), "label": label})

    df = pd.DataFrame(records)
    return df

df_all = explore_dataset(DATASET_ROOT, KEEP_CLASSES)

if df_all.empty:
    # ── Fallback: flat folder with label encoded in filename ──────────────────
    records = []
    for img_file in sorted(DATASET_ROOT.rglob("*.jpg")):
        # some releases use filename prefix like "letter_001.jpg"
        label = img_file.stem.split("_")[0].lower()
        records.append({"path": str(img_file), "label": label})
    df_all = pd.DataFrame(records)

print(f"✅ Dataset loaded — {len(df_all)} images across {df_all['label'].nunique()} classes\n")
print(df_all["label"].value_counts().to_string())

# ── Class distribution bar chart ──────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(10, 5))
counts = df_all["label"].value_counts()
colors = plt.cm.tab10(np.linspace(0, 1, len(counts)))
bars = ax.bar(counts.index, counts.values, color=colors, edgecolor="black", alpha=0.85)
for bar, v in zip(bars, counts.values):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
            str(v), ha="center", va="bottom", fontsize=9, fontweight="bold")
ax.set_title("Tobacco3482 — Document Class Distribution", fontsize=14, fontweight="bold")
ax.set_xlabel("Document Class", fontsize=12)
ax.set_ylabel("Number of Images", fontsize=12)
ax.grid(axis="y", linestyle="--", alpha=0.5)
plt.tight_layout()
plt.savefig(DIRS["outputs"] / "class_distribution.png", dpi=150)
plt.show()
print(f"✅ Chart saved → outputs/class_distribution.png")


# ██████████████████████████████████████████████████████████████████████████████
# CELL 5 ── Image Preprocessor
# ██████████████████████████████████████████████████████████████████████████████

class ImagePreprocessor:
    """
    Applies a sequence of classical CV techniques to improve OCR accuracy:
      1. Convert to grayscale
      2. Fast Non-Local Means denoising
      3. Deskew (minAreaRect-based rotation correction)
      4. Adaptive Gaussian thresholding (binarization)
      5. 2× Lanczos upscaling
    """

    @staticmethod
    def load_gray(path: str) -> np.ndarray:
        """Load image and convert to grayscale."""
        img = cv2.imread(path)
        if img is None:
            img = np.array(Image.open(path).convert("L"))
            return img
        return cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    @staticmethod
    def denoise(gray: np.ndarray) -> np.ndarray:
        return cv2.fastNlMeansDenoising(gray, h=15, templateWindowSize=7, searchWindowSize=21)

    @staticmethod
    def deskew(gray: np.ndarray) -> np.ndarray:
        """Correct rotation up to ±45 degrees."""
        thresh = cv2.threshold(gray, 0, 255,
                               cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)[1]
        coords = np.column_stack(np.where(thresh > 0))
        if len(coords) < 10:
            return gray
        angle = cv2.minAreaRect(coords)[-1]
        angle = -(90 + angle) if angle < -45 else -angle
        if abs(angle) < 0.5:           # skip tiny corrections
            return gray
        h, w = gray.shape
        M = cv2.getRotationMatrix2D((w // 2, h // 2), angle, 1.0)
        return cv2.warpAffine(gray, M, (w, h),
                              flags=cv2.INTER_CUBIC,
                              borderMode=cv2.BORDER_REPLICATE)

    @staticmethod
    def binarize(gray: np.ndarray) -> np.ndarray:
        """Adaptive thresholding handles uneven illumination."""
        return cv2.adaptiveThreshold(
            gray, 255,
            cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
            cv2.THRESH_BINARY,
            blockSize=11, C=2
        )

    @staticmethod
    def upscale(img: np.ndarray, scale: int = 2) -> np.ndarray:
        h, w = img.shape[:2]
        return cv2.resize(img, (w * scale, h * scale),
                          interpolation=cv2.INTER_LANCZOS4)

    def preprocess(self, path: str, save_path: str = None) -> np.ndarray:
        gray   = self.load_gray(path)
        gray   = self.denoise(gray)
        gray   = self.deskew(gray)
        binary = self.binarize(gray)
        result = self.upscale(binary, 2)
        if save_path:
            os.makedirs(os.path.dirname(save_path), exist_ok=True)
            cv2.imwrite(save_path, result)
        return result

    def show_stages(self, path: str):
        """Visualise each preprocessing stage side-by-side."""
        original = cv2.cvtColor(cv2.imread(path), cv2.COLOR_BGR2RGB)
        gray     = self.load_gray(path)
        denoised = self.denoise(gray.copy())
        deskewed = self.deskew(denoised.copy())
        binary   = self.binarize(deskewed.copy())
        upscaled = self.upscale(binary.copy(), 2)

        stages   = [original, gray, denoised, binary, upscaled]
        titles   = ["Original", "Grayscale", "Denoised", "Binarized", "Upscaled ×2"]
        cmaps    = [None, "gray", "gray", "gray", "gray"]

        fig, axes = plt.subplots(1, 5, figsize=(20, 4))
        for ax, img, title, cmap in zip(axes, stages, titles, cmaps):
            ax.imshow(img, cmap=cmap)
            ax.set_title(title, fontsize=11, fontweight="bold")
            ax.axis("off")
        plt.suptitle("Preprocessing Pipeline — Stage Visualisation",
                     fontsize=14, fontweight="bold")
        plt.tight_layout()
        plt.savefig(DIRS["outputs"] / "preprocessing_stages.png", dpi=150)
        plt.show()
        print("✅ Saved → outputs/preprocessing_stages.png")


preprocessor = ImagePreprocessor()

# Show preprocessing stages on one sample image
sample_path = df_all.iloc[0]["path"]
preprocessor.show_stages(sample_path)


# ██████████████████████████████████████████████████████████████████████████████
# CELL 6 ── OCR Engine & Field Extractor
# ██████████████████████████████████████████████████████████████████████████████

class OCREngine:
    """
    Wraps Tesseract OCR.
    - extract_text()            → cleaned string
    - extract_with_confidence() → (cleaned string, avg_confidence 0-1)
    """
    CONFIG = "--oem 3 --psm 6"   # oem3 = LSTM+Legacy; psm6 = uniform text block

    def _clean(self, text: str) -> str:
        text = re.sub(r"[^\x20-\x7E\n]", " ", text)   # keep printable ASCII
        text = re.sub(r" {2,}", " ", text)              # collapse spaces
        text = re.sub(r"\n{3,}", "\n\n", text)          # max 2 blank lines
        return text.strip()

    def extract_text(self, image_array: np.ndarray) -> str:
        pil_img = Image.fromarray(image_array)
        raw     = pytesseract.image_to_string(pil_img, config=self.CONFIG)
        return self._clean(raw)

    def extract_with_confidence(self, image_array: np.ndarray):
        pil_img = Image.fromarray(image_array)
        data    = pytesseract.image_to_data(
            pil_img, config=self.CONFIG,
            output_type=pytesseract.Output.DICT
        )
        words   = [
            (data["text"][i], int(data["conf"][i]))
            for i in range(len(data["text"]))
            if int(data["conf"][i]) > 0 and data["text"][i].strip()
        ]
        text     = " ".join(w for w, _ in words)
        avg_conf = np.mean([c for _, c in words]) / 100 if words else 0.0
        return self._clean(text), round(float(avg_conf), 4)


class FieldExtractor:
    """
    Regex-based Named Entity extraction from OCR text.
    Works on ALL Tobacco3482 document types.
    """
    PATTERNS = {
        "invoice_number": [
            r"\bINV[-\s]?(\d{3,8})\b",
            r"Invoice\s*(?:No|Number|#)[:\s]*([A-Z0-9\-]+)"
        ],
        "contract_id": [
            r"\bCTR[-\s]?(\d{3,8})\b",
            r"Contract\s*(?:ID|No|Number)[:\s]*([A-Z0-9\-]+)"
        ],
        "report_id": [
            r"\bRPT[-\s]?(\d{3,8})\b",
            r"Report\s*(?:ID|No|Number)[:\s]*([A-Z0-9\-]+)"
        ],
        "date": [
            r"\b(\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4})\b",
            r"\b(\d{1,2}\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\w*\s+\d{4})\b",
            r"\b((?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\w*\s+\d{1,2},?\s+\d{4})\b",
        ],
        "amount": [
            r"\$\s*([\d,]+(?:\.\d{2})?)",
            r"(?:USD|EUR|GBP)\s*([\d,]+(?:\.\d{2})?)"
        ],
        "email": [
            r"[\w\.\-]+@[\w\.\-]+\.\w{2,}"
        ],
        "phone": [
            r"\(?\d{3}\)?[\s\-\.]\d{3}[\s\-\.]\d{4}"
        ],
        "percentage": [
            r"(\d{1,3}(?:\.\d+)?)\s*%"
        ],
    }

    def extract(self, text: str) -> dict:
        result = {}
        for field, patterns in self.PATTERNS.items():
            for pat in patterns:
                m = re.search(pat, text, re.IGNORECASE)
                if m:
                    result[field] = m.group(1) if m.lastindex else m.group(0)
                    break
        return result


ocr_engine     = OCREngine()
field_extractor = FieldExtractor()

# Quick smoke test
sample_arr = preprocessor.preprocess(sample_path)
sample_text, sample_conf = ocr_engine.extract_with_confidence(sample_arr)
print(f"OCR Confidence on sample: {sample_conf:.2%}")
print(f"Extracted fields: {field_extractor.extract(sample_text)}")
print(f"Text snippet: {sample_text[:200]!r}")


# ██████████████████████████████████████████████████████████████████████████████
# CELL 7 ── Build OCR Corpus (with progress bar)
# ██████████████████████████████████████████████████████████████████████████████
#
# IMPORTANT NOTE ON SPEED:
#   Tesseract takes ~0.5–2 s per image.
#   Full Tobacco3482 (3482 images) → ~30–60 minutes on CPU.
#
#   We sample MAX_PER_CLASS images per class so the notebook runs in <10 min.
#   Increase MAX_PER_CLASS (or set to None) for a full run.
#
MAX_PER_CLASS = 80    # ← increase to None to use all images (slower)
CORPUS_CACHE  = ROOT / "corpus_cache.pkl"

def build_corpus(df: pd.DataFrame,
                 max_per_class: int = None,
                 cache_path: Path = None) -> pd.DataFrame:
    """
    Run OCR on every image and return a DataFrame with columns:
        path | label | ocr_text | ocr_confidence
    Uses a pickle cache so re-running is instant.
    """
    if cache_path and cache_path.exists():
        print(f"⚡ Loading cached corpus from {cache_path}")
        corpus_df = pd.read_pickle(cache_path)
        print(f"   {len(corpus_df)} entries loaded.")
        return corpus_df

    # Sample per class
    if max_per_class:
        df = (df.groupby("label", group_keys=False)
                .apply(lambda g: g.sample(min(len(g), max_per_class),
                                          random_state=42)))
        df = df.reset_index(drop=True)

    print(f"Running OCR on {len(df)} images ({df['label'].nunique()} classes)…")
    print("This may take several minutes — grab a coffee ☕\n")

    records = []
    for _, row in tqdm(df.iterrows(), total=len(df), desc="OCR"):
        try:
            arr      = preprocessor.preprocess(row["path"])
            text, cf = ocr_engine.extract_with_confidence(arr)
            records.append({
                "path":           row["path"],
                "label":          row["label"],
                "ocr_text":       text,
                "ocr_confidence": cf,
            })
        except Exception as e:
            # Skip corrupt / unreadable images silently
            records.append({
                "path":           row["path"],
                "label":          row["label"],
                "ocr_text":       "",
                "ocr_confidence": 0.0,
            })

    corpus_df = pd.DataFrame(records)

    # Drop rows where OCR returned nothing useful
    corpus_df = corpus_df[corpus_df["ocr_text"].str.strip().str.len() > 10]
    corpus_df = corpus_df.reset_index(drop=True)

    if cache_path:
        corpus_df.to_pickle(cache_path)
        print(f"\n✅ Corpus cached → {cache_path}")

    return corpus_df


corpus_df = build_corpus(df_all, max_per_class=MAX_PER_CLASS,
                          cache_path=CORPUS_CACHE)

print(f"\nCorpus size : {len(corpus_df)} usable OCR extractions")
print(corpus_df["label"].value_counts().to_string())
print(f"\nMean OCR confidence : {corpus_df['ocr_confidence'].mean():.2%}")


# ██████████████████████████████████████████████████████████████████████████████
# CELL 8 ── Train & Evaluate ML Classifiers
# ██████████████████████████████████████████████████████████████████████████████

class DocumentClassifier:
    """
    Trains Naive Bayes, SVM, and Random Forest on TF-IDF features.
    Auto-selects and saves the best model.
    """

    MODELS = {
        "Naive Bayes": Pipeline([
            ("tfidf", TfidfVectorizer(max_features=10000,
                                      ngram_range=(1, 2),
                                      sublinear_tf=True,
                                      min_df=2)),
            ("clf",   MultinomialNB(alpha=0.1)),
        ]),
        "SVM": Pipeline([
            ("tfidf", TfidfVectorizer(max_features=10000,
                                      ngram_range=(1, 2),
                                      sublinear_tf=True,
                                      min_df=2)),
            ("clf",   LinearSVC(C=1.0, max_iter=3000)),
        ]),
        "Random Forest": Pipeline([
            ("tfidf", TfidfVectorizer(max_features=5000,
                                      ngram_range=(1, 1),
                                      sublinear_tf=True,
                                      min_df=2)),
            ("clf",   RandomForestClassifier(n_estimators=200,
                                              n_jobs=-1,
                                              random_state=42)),
        ]),
    }

    def __init__(self):
        self.best_pipeline = None
        self.best_name     = None
        self.le            = LabelEncoder()
        self.metrics_      = {}
        self.X_test        = None
        self.y_test        = None

    def train(self, texts, labels, test_size=0.2, cv_folds=5):
        y = self.le.fit_transform(labels)
        X_tr, X_te, y_tr, y_te = train_test_split(
            texts, y,
            test_size=test_size,
            random_state=42,
            stratify=y
        )
        self.X_test = X_te
        self.y_test = y_te

        print(f"Train: {len(X_tr)}  |  Test: {len(X_te)}\n")
        print(f"  {'Model':<18} {'Acc':>7} {'Prec':>7} {'Rec':>7} {'F1':>7} {'CV Mean':>9} {'CV Std':>8}")
        print("  " + "-"*67)

        best_acc = -1
        for name, pipeline in self.MODELS.items():
            pipeline.fit(X_tr, y_tr)
            y_pred = pipeline.predict(X_te)

            acc  = accuracy_score(y_te, y_pred)
            prec = precision_score(y_te, y_pred, average="weighted", zero_division=0)
            rec  = recall_score(y_te, y_pred,    average="weighted", zero_division=0)
            f1   = f1_score(y_te, y_pred,        average="weighted", zero_division=0)

            cv = cross_val_score(
                pipeline, texts, y,
                cv=StratifiedKFold(cv_folds, shuffle=True, random_state=42),
                scoring="accuracy", n_jobs=-1
            )

            self.metrics_[name] = {
                "accuracy":        acc,
                "precision":       prec,
                "recall":          rec,
                "f1":              f1,
                "cv_mean":         float(cv.mean()),
                "cv_std":          float(cv.std()),
                "confusion_matrix": confusion_matrix(y_te, y_pred).tolist(),
                "classification_report": classification_report(
                    y_te, y_pred,
                    target_names=self.le.classes_,
                    output_dict=True
                ),
                "pipeline":        pipeline,
            }

            print(f"  [{name:<16}]  {acc:>7.4f} {prec:>7.4f} {rec:>7.4f} {f1:>7.4f} "
                  f"  {cv.mean():>7.4f}   {cv.std():>6.4f}")

            if acc > best_acc:
                best_acc           = acc
                self.best_pipeline = pipeline
                self.best_name     = name

        print(f"\n🏆 Best model: {self.best_name}  (accuracy = {best_acc:.4f})")
        return self.metrics_

    def predict(self, text: str):
        """Returns (label_string, confidence_float)."""
        y_pred = self.best_pipeline.predict([text])[0]
        label  = self.le.inverse_transform([y_pred])[0]

        clf = self.best_pipeline.named_steps["clf"]
        if hasattr(clf, "predict_proba"):
            conf = float(self.best_pipeline.predict_proba([text]).max())
        else:
            # LinearSVC → softmax over decision scores
            scores = self.best_pipeline.decision_function([text])
            e      = np.exp(scores - scores.max())
            conf   = float((e / e.sum()).max())

        return label, round(conf, 4)

    def save(self, path: Path):
        payload = {
            "pipeline":   self.best_pipeline,
            "name":       self.best_name,
            "le":         self.le,
            "metrics":    {k: {mk: mv for mk, mv in v.items() if mk != "pipeline"}
                           for k, v in self.metrics_.items()},
        }
        with open(path, "wb") as f:
            pickle.dump(payload, f)
        print(f"✅ Model saved → {path}")

    @classmethod
    def load(cls, path: Path):
        with open(path, "rb") as f:
            data = pickle.load(f)
        obj = cls()
        obj.best_pipeline = data["pipeline"]
        obj.best_name     = data["name"]
        obj.le            = data["le"]
        obj.metrics_      = data.get("metrics", {})
        return obj


# ── Train ─────────────────────────────────────────────────────────────────────
classifier = DocumentClassifier()
metrics    = classifier.train(
    corpus_df["ocr_text"].tolist(),
    corpus_df["label"].tolist()
)
classifier.save(DIRS["models"] / "classifier.pkl")


# ██████████████████████████████████████████████████████████████████████████████
# CELL 9 ── Evaluation Charts & Reports
# ██████████████████████████████████████████████████████████████████████████████

classes = classifier.le.classes_

# ── 1. Confusion Matrix (best model) ─────────────────────────────────────────
cm = np.array(metrics[classifier.best_name]["confusion_matrix"])

fig, ax = plt.subplots(figsize=(max(8, len(classes)), max(6, len(classes) - 1)))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=classes, yticklabels=classes,
            linewidths=0.5, linecolor="#CBD5E1",
            annot_kws={"size": 10})
ax.set_title(f"Confusion Matrix — {classifier.best_name}",
             fontsize=14, fontweight="bold", pad=15)
ax.set_xlabel("Predicted Label", fontsize=12)
ax.set_ylabel("True Label",      fontsize=12)
plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig(DIRS["outputs"] / "confusion_matrix.png", dpi=150)
plt.show()
print("✅ Saved → outputs/confusion_matrix.png")

# ── 2. Model Comparison Bar Chart ────────────────────────────────────────────
model_names = list(metrics.keys())
metric_keys = ["accuracy", "precision", "recall", "f1"]
metric_vals = {m: [metrics[n][m] for n in model_names] for m in metric_keys}

x  = np.arange(len(model_names))
w  = 0.20
fig, ax = plt.subplots(figsize=(11, 6))
colours = ["#3B82F6", "#F97316", "#22C55E", "#EF4444"]
for i, (metric, colour) in enumerate(zip(metric_keys, colours)):
    bars = ax.bar(x + i * w, metric_vals[metric], width=w,
                  label=metric.title(), color=colour, alpha=0.85, edgecolor="black")
    for bar in bars:
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.005,
                f"{bar.get_height():.3f}",
                ha="center", va="bottom", fontsize=7.5, fontweight="bold")

ax.set_xticks(x + 1.5 * w)
ax.set_xticklabels(model_names, fontsize=12)
ax.set_ylim(0, 1.12)
ax.set_ylabel("Score", fontsize=12)
ax.set_title("ML Model Comparison — Accuracy, Precision, Recall, F1",
             fontsize=13, fontweight="bold")
ax.legend(fontsize=11)
ax.grid(axis="y", linestyle="--", alpha=0.4)
plt.tight_layout()
plt.savefig(DIRS["outputs"] / "model_comparison.png", dpi=150)
plt.show()
print("✅ Saved → outputs/model_comparison.png")

# ── 3. Cross-Validation Score Chart ──────────────────────────────────────────
cv_means = [metrics[n]["cv_mean"] for n in model_names]
cv_stds  = [metrics[n]["cv_std"]  for n in model_names]

fig, ax = plt.subplots(figsize=(8, 5))
bar_colours = ["#3B82F6", "#F97316", "#22C55E"]
bars = ax.bar(model_names, cv_means, yerr=cv_stds, capsize=8,
              color=bar_colours, alpha=0.85, edgecolor="black")
for bar, mean in zip(bars, cv_means):
    ax.text(bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.015,
            f"{mean:.4f}",
            ha="center", fontsize=11, fontweight="bold")
ax.set_ylim(0, 1.15)
ax.set_ylabel("CV Accuracy (mean ± std)", fontsize=12)
ax.set_title("5-Fold Stratified Cross-Validation Accuracy",
             fontsize=13, fontweight="bold")
ax.grid(axis="y", linestyle="--", alpha=0.4)
plt.tight_layout()
plt.savefig(DIRS["outputs"] / "cv_scores.png", dpi=150)
plt.show()
print("✅ Saved → outputs/cv_scores.png")

# ── 4. Per-Class F1 Score ─────────────────────────────────────────────────────
report      = metrics[classifier.best_name]["classification_report"]
class_f1    = {k: v["f1-score"] for k, v in report.items()
               if k in classes}
sorted_keys = sorted(class_f1, key=class_f1.get, reverse=True)
vals        = [class_f1[k] for k in sorted_keys]

fig, ax = plt.subplots(figsize=(10, 5))
palette = plt.cm.RdYlGn(np.linspace(0.2, 0.9, len(sorted_keys)))
bars    = ax.barh(sorted_keys, vals, color=palette, edgecolor="black", alpha=0.85)
for bar, v in zip(bars, vals):
    ax.text(bar.get_width() + 0.005, bar.get_y() + bar.get_height() / 2,
            f"{v:.3f}", va="center", fontsize=9, fontweight="bold")
ax.set_xlim(0, 1.12)
ax.set_xlabel("F1-Score", fontsize=12)
ax.set_title(f"Per-Class F1-Score — {classifier.best_name}",
             fontsize=13, fontweight="bold")
ax.grid(axis="x", linestyle="--", alpha=0.4)
plt.tight_layout()
plt.savefig(DIRS["outputs"] / "per_class_f1.png", dpi=150)
plt.show()
print("✅ Saved → outputs/per_class_f1.png")

# ── 5. Print full metrics table ───────────────────────────────────────────────
print("\n" + "="*80)
print(f"  {'Model':<18} {'Accuracy':>9} {'Precision':>10} {'Recall':>8} "
      f"{'F1':>8} {'CV Mean':>9} {'CV Std':>8}")
print("  " + "-"*80)
for name, m in metrics.items():
    marker = " ← BEST" if name == classifier.best_name else ""
    print(f"  {name:<18} {m['accuracy']:>9.4f} {m['precision']:>10.4f} "
          f"{m['recall']:>8.4f} {m['f1']:>8.4f} {m['cv_mean']:>9.4f} "
          f"{m['cv_std']:>8.4f}{marker}")
print("="*80)

# ── Save metrics CSV ──────────────────────────────────────────────────────────
metrics_rows = []
for name, m in metrics.items():
    metrics_rows.append({
        "model":     name,
        "accuracy":  m["accuracy"],
        "precision": m["precision"],
        "recall":    m["recall"],
        "f1":        m["f1"],
        "cv_mean":   m["cv_mean"],
        "cv_std":    m["cv_std"],
        "best":      name == classifier.best_name,
    })
metrics_df = pd.DataFrame(metrics_rows)
metrics_df.to_csv(DIRS["outputs"] / "model_metrics.csv", index=False)
print(f"\n✅ model_metrics.csv saved → outputs/")


# ██████████████████████████████████████████████████████████████████████████████
# CELL 10 ── Full OCR Pipeline (single-image inference)
# ██████████████████████████████████████████████████████████████████████████████

class OCRPipeline:
    """
    End-to-end pipeline:
        image path → preprocess → OCR → classify → extract fields → dict
    """

    def __init__(self, classifier: DocumentClassifier):
        self.prep      = ImagePreprocessor()
        self.ocr       = OCREngine()
        self.extractor = FieldExtractor()
        self.clf       = classifier

    def process(self, image_path: str, verbose: bool = False) -> dict:
        t0 = time.time()

        # Step 1: Preprocess
        arr = self.prep.preprocess(image_path)

        # Step 2: OCR
        text, ocr_conf = self.ocr.extract_with_confidence(arr)

        # Step 3: Classify
        doc_type, clf_conf = self.clf.predict(text)

        # Step 4: Extract structured fields
        fields = self.extractor.extract(text)

        elapsed = round(time.time() - t0, 2)
        result  = {
            "file":             image_path,
            "doc_type":         doc_type,
            "clf_confidence":   clf_conf,
            "ocr_confidence":   ocr_conf,
            "processing_time_s": elapsed,
            "extracted_fields": fields,
            "raw_text_snippet": text[:400],
        }
        if verbose:
            print(json.dumps(
                {k: v for k, v in result.items() if k != "raw_text_snippet"},
                indent=2
            ))
            print(f"  text snippet: {text[:200]!r}")
        return result


pipeline = OCRPipeline(classifier)

# ── Demo: run one image from each class ──────────────────────────────────────
print("=" * 60)
print("DEMO — One sample from each class")
print("=" * 60)
demo_results = []
for cls in corpus_df["label"].unique():
    sample = corpus_df[corpus_df["label"] == cls].iloc[0]
    print(f"\n▶  True label: {cls}")
    r = pipeline.process(sample["path"], verbose=True)
    demo_results.append(r)


# ██████████████████████████████████████████████████████████████████████████████
# CELL 11 ── Batch Processing
# ██████████████████████████████████████████████████████████████████████████████

def batch_process(image_paths: list, output_csv: str = "batch_results.csv") -> pd.DataFrame:
    """
    Process a list of image paths through the full OCR pipeline.
    Returns a DataFrame and saves results to CSV.
    """
    print(f"Batch processing {len(image_paths)} images…")
    rows = []
    for i, path in enumerate(image_paths, 1):
        try:
            r = pipeline.process(str(path))
            row = {
                "file":            r["file"],
                "doc_type":        r["doc_type"],
                "clf_confidence":  r["clf_confidence"],   # ← fixed column name
                "ocr_confidence":  r["ocr_confidence"],   # ← fixed column name
                "processing_time": r["processing_time_s"],
            }
            # Flatten extracted fields as separate columns
            for field_key, field_val in r["extracted_fields"].items():
                row[f"field_{field_key}"] = field_val
            rows.append(row)
        except Exception as e:
            rows.append({
                "file":    str(path),
                "error":   str(e),
                "doc_type": "",
                "clf_confidence": 0.0,
                "ocr_confidence": 0.0,
            })

        if i % 20 == 0:
            print(f"  ✓ Processed {i}/{len(image_paths)}")

    df = pd.DataFrame(rows)
    csv_path = DIRS["outputs"] / output_csv
    df.to_csv(csv_path, index=False)
    print(f"\n✅ Batch done — {len(df)} rows saved → outputs/{output_csv}")
    return df


# Run batch on a sample of 50 images (increase as needed)
batch_paths = (corpus_df.groupby("label")
               .apply(lambda g: g.head(5))
               .reset_index(drop=True)["path"]
               .tolist())

batch_df = batch_process(batch_paths)

# ── Display sample results (correct column names) ─────────────────────────────
print("\nSample batch results:")
display_cols = ["file", "doc_type", "clf_confidence", "ocr_confidence"]
print(batch_df[display_cols].head(10).to_string(index=False))

# ── Accuracy vs ground truth where available ──────────────────────────────────
# Merge with corpus_df to get true labels
batch_df["filename"] = batch_df["file"].apply(lambda x: str(x))
corpus_sample = corpus_df[corpus_df["path"].isin(batch_paths)].copy()
corpus_sample["filename"] = corpus_sample["path"].astype(str)
merged = batch_df.merge(corpus_sample[["filename","label"]], on="filename", how="left")
if "label" in merged.columns and merged["label"].notna().any():
    valid = merged.dropna(subset=["label","doc_type"])
    if len(valid) > 0:
        batch_acc = (valid["doc_type"] == valid["label"]).mean()
        print(f"\n✅ Batch classification accuracy vs ground truth: {batch_acc:.2%}")


# ██████████████████████████████████████████████████████████████████████████████
# CELL 12 ── Streamlit Frontend App (saved as app.py)
# ██████████████████████████████████████████████████████████████████████████████

STREAMLIT_CODE = r'''
# ── OCR Document Extraction — Streamlit Frontend ─────────────────────────────
import streamlit as st
import pytesseract, pickle, re, cv2, json, time
import numpy as np
from PIL import Image
from pathlib import Path

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="OCR Document Extraction",
    page_icon="📄",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ── Load model ────────────────────────────────────────────────────────────────
MODEL_PATH = Path("ocr_project/models/classifier.pkl")

@st.cache_resource(show_spinner="Loading ML model…")
def load_model():
    with open(MODEL_PATH, "rb") as f:
        return pickle.load(f)

if not MODEL_PATH.exists():
    st.error("❌ Model not found. Run the training cells first.")
    st.stop()

model_data = load_model()
pipeline_obj = model_data["pipeline"]
le           = model_data["le"]

# ── Helpers ───────────────────────────────────────────────────────────────────
def preprocess_image(pil_img: Image.Image) -> np.ndarray:
    """BGR → Gray → Denoise → Binarize → Upscale."""
    arr  = cv2.cvtColor(np.array(pil_img.convert("RGB")), cv2.COLOR_RGB2GRAY)
    arr  = cv2.fastNlMeansDenoising(arr, h=15)
    arr  = cv2.adaptiveThreshold(arr, 255,
                                  cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                  cv2.THRESH_BINARY, 11, 2)
    h, w = arr.shape
    arr  = cv2.resize(arr, (w * 2, h * 2), interpolation=cv2.INTER_LANCZOS4)
    return arr

def run_ocr(arr: np.ndarray):
    pil_img = Image.fromarray(arr)
    data    = pytesseract.image_to_data(pil_img, config="--oem 3 --psm 6",
                                         output_type=pytesseract.Output.DICT)
    words   = [(data["text"][i], int(data["conf"][i]))
               for i in range(len(data["text"]))
               if int(data["conf"][i]) > 0 and data["text"][i].strip()]
    text    = " ".join(w for w, _ in words)
    text    = re.sub(r"[^\x20-\x7E\n]", " ", text)
    text    = re.sub(r" {2,}", " ", text).strip()
    conf    = np.mean([c for _, c in words]) / 100 if words else 0.0
    return text, round(float(conf), 4)

PATTERNS = {
    "invoice_number": r"\bINV[-\s]?(\d{3,8})\b",
    "contract_id":    r"\bCTR[-\s]?(\d{3,8})\b",
    "report_id":      r"\bRPT[-\s]?(\d{3,8})\b",
    "date":           r"\b(\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4})\b",
    "amount":         r"\$\s*([\d,]+(?:\.\d{2})?)",
    "email":          r"[\w\.\-]+@[\w\.\-]+\.\w{2,}",
    "percentage":     r"(\d{1,3}(?:\.\d+)?)\s*%",
}

def extract_fields(text: str) -> dict:
    return {
        k: (m.group(1) if (m := re.search(p, text, re.I)) and m.lastindex
            else m.group(0) if (m := re.search(p, text, re.I)) else "—")
        for k, p in PATTERNS.items()
    }

def classify(text: str):
    y_pred = pipeline_obj.predict([text])[0]
    label  = le.inverse_transform([y_pred])[0]
    clf    = pipeline_obj.named_steps["clf"]
    if hasattr(clf, "predict_proba"):
        conf = float(pipeline_obj.predict_proba([text]).max())
    else:
        sc   = pipeline_obj.decision_function([text])
        e    = np.exp(sc - sc.max())
        conf = float((e / e.sum()).max())
    return label, round(conf, 4)

# ── Sidebar ───────────────────────────────────────────────────────────────────
st.sidebar.title("⚙️ Settings")
st.sidebar.markdown("---")
st.sidebar.info(
    f"**Model:** {model_data['name']}\n\n"
    f"**Classes:** {', '.join(le.classes_)}"
)
st.sidebar.markdown("---")
st.sidebar.markdown("**How it works:**\n"
    "1. Upload a scanned document\n"
    "2. Image is preprocessed (OpenCV)\n"
    "3. Text extracted via Tesseract OCR\n"
    "4. Document classified by ML model\n"
    "5. Key fields extracted by regex")

# ── Main UI ───────────────────────────────────────────────────────────────────
st.title("📄 OCR Document Processing & Data Extraction")
st.markdown(
    "Upload a scanned corporate document — **invoice, contract, report, letter, "
    "email, form, memo** — and the system will extract structured data automatically."
)

uploaded = st.file_uploader(
    "📁 Upload Document Image",
    type=["png", "jpg", "jpeg"],
    help="Supported formats: PNG, JPG, JPEG"
)

if uploaded:
    pil_img = Image.open(uploaded).convert("RGB")
    col1, col2 = st.columns([1, 1], gap="large")

    with col1:
        st.subheader("📷 Uploaded Document")
        st.image(pil_img, use_column_width=True)

    with col2:
        st.subheader("🔍 Extraction Results")

        with st.spinner("🔄 Preprocessing image…"):
            arr = preprocess_image(pil_img)

        with st.spinner("📝 Running OCR…"):
            t0        = time.time()
            text, ocr_conf = run_ocr(arr)
            ocr_time  = time.time() - t0

        with st.spinner("🤖 Classifying document…"):
            doc_type, clf_conf = classify(text)

        with st.spinner("🔎 Extracting fields…"):
            fields = extract_fields(text)

        total_time = round(time.time() - t0 + ocr_time, 2)

        # ── Metrics ───────────────────────────────────────────────────────────
        m1, m2, m3 = st.columns(3)
        m1.metric("📂 Document Type",       doc_type.upper())
        m2.metric("🤖 Classification Score", f"{clf_conf*100:.1f}%")
        m3.metric("📝 OCR Confidence",       f"{ocr_conf*100:.1f}%")

        st.markdown(f"⏱️ Processing time: **{total_time:.2f} s**")
        st.markdown("---")

        # ── Extracted fields ──────────────────────────────────────────────────
        st.subheader("📋 Extracted Fields")
        found    = {k: v for k, v in fields.items() if v != "—"}
        not_found = {k: v for k, v in fields.items() if v == "—"}

        if found:
            for k, v in found.items():
                st.success(f"**{k.replace('_',' ').title()}:** {v}")
        else:
            st.info("No structured fields detected in this document.")

        with st.expander("Fields not found"):
            for k in not_found:
                st.write(f"• {k.replace('_',' ').title()}")

        # ── Raw text ──────────────────────────────────────────────────────────
        with st.expander("📄 Raw OCR Text (first 600 chars)"):
            st.text(text[:600] if text else "No text extracted.")

        # ── Download ──────────────────────────────────────────────────────────
        st.markdown("---")
        result_json = {
            "file":           uploaded.name,
            "doc_type":       doc_type,
            "clf_confidence": clf_conf,
            "ocr_confidence": ocr_conf,
            "fields":         fields,
            "raw_text":       text[:1000],
        }
        st.download_button(
            label="⬇️ Download JSON Result",
            data=json.dumps(result_json, indent=2),
            file_name=f"{Path(uploaded.name).stem}_extracted.json",
            mime="application/json"
        )
else:
    st.info("👆 Upload a document image above to get started.")
    st.markdown("---")
    st.markdown("### 📌 Supported Document Types")
    doc_types = {
        "📋 Invoice":    "Extracts invoice number, amounts, dates, vendor info",
        "📝 Contract":   "Extracts contract ID, parties, dates, value",
        "📊 Report":     "Extracts report ID, revenue figures, KPIs",
        "✉️ Letter":     "Extracts dates, names, addresses",
        "📧 Email":      "Extracts email addresses, dates, subjects",
        "📑 Form":       "Extracts field labels and values",
        "📌 Memo":       "Extracts dates, recipients, key points",
        "📰 Other":      "General OCR extraction for any document",
    }
    cols = st.columns(2)
    for i, (dtype, desc) in enumerate(doc_types.items()):
        cols[i % 2].markdown(f"**{dtype}**\n{desc}")
'''

with open("app.py", "w") as f:
    f.write(STREAMLIT_CODE)

print("✅ Streamlit app saved as app.py")


# ██████████████████████████████████████████████████████████████████████████████
# CELL 13 ── Launch Frontend in Google Colab (via ngrok)
# ██████████████████████████████████████████████████████████████████████████████
"""
# Run this cell to launch the Streamlit frontend in Colab
# You'll get a public URL you can open in any browser

!pip install pyngrok -q
from pyngrok import ngrok
import subprocess, time, os

# Kill any existing streamlit
os.system("pkill -f streamlit 2>/dev/null || true")
time.sleep(2)

# Start Streamlit in background
proc = subprocess.Popen(
    ["streamlit", "run", "app.py",
     "--server.port=8501",
     "--server.headless=true",
     "--server.enableCORS=false"],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL
)
time.sleep(6)

# Create ngrok tunnel
tunnel = ngrok.connect(8501)
print("=" * 55)
print("🌐  FRONTEND URL:", tunnel.public_url)
print("=" * 55)
print("Open the URL above in a new browser tab.")
print("To stop: proc.terminate(); ngrok.disconnect(tunnel.public_url)")
"""


# ██████████████████████████████████████████████████████████████████████████████
# CELL 14 ── Final Project Summary
# ██████████████████████████████████████████████████████████████████████████████

print("\n" + "=" * 65)
print("  PROJECT SUMMARY — OCR Document Extraction System")
print("=" * 65)
print(f"  Dataset         : Tobacco3482 (real scanned corporate docs)")
print(f"  Images used     : {len(corpus_df)}")
print(f"  Classes         : {', '.join(corpus_df['label'].unique())}")
print(f"  Best classifier : {classifier.best_name}")
bm = metrics[classifier.best_name]
print(f"  Accuracy        : {bm['accuracy']:.4f}")
print(f"  Precision       : {bm['precision']:.4f}")
print(f"  Recall          : {bm['recall']:.4f}")
print(f"  F1-Score        : {bm['f1']:.4f}")
print(f"  CV Accuracy     : {bm['cv_mean']:.4f} ± {bm['cv_std']:.4f}")
print("=" * 65)
print("\n  Output files:")
for f in sorted(DIRS["outputs"].glob("*")):
    size = f.stat().st_size // 1024
    print(f"    {f.name:<35} {size:>4} KB")
print(f"\n  Model : {DIRS['models'] / 'classifier.pkl'}")
print(f"  App   : app.py  (run with: streamlit run app.py)")
print("\n✅ All done! Upload to GitHub and share the public link.")
print("=" * 65)


# ██████████████████████████████████████████████████████████████████████████████
# CELL 15 ── GitHub Upload Helper (optional)
# ██████████████████████████████████████████████████████████████████████████████
"""
# Run this to push everything to a new GitHub repo automatically.
# Replace YOUR_GITHUB_TOKEN and YOUR_USERNAME before running.

import subprocess

GITHUB_TOKEN    = "your_github_token_here"     # ← replace
GITHUB_USERNAME = "your_username_here"         # ← replace
REPO_NAME       = "ocr-document-extraction"

# Create repo via GitHub API
import requests
headers = {"Authorization": f"token {GITHUB_TOKEN}",
           "Accept": "application/vnd.github.v3+json"}
resp = requests.post("https://api.github.com/user/repos",
                     headers=headers,
                     json={"name": REPO_NAME, "private": False,
                           "description": "OCR Document Processing & Data Extraction – Industry Project"})
print("Repo created:", resp.status_code)

# Write README
readme = '''# OCR Document Processing & Data Extraction
Industry Project — Vision Intelligence & Machine Learning

## Setup
```bash
pip install pytesseract opencv-python-headless pillow scikit-learn pandas matplotlib seaborn streamlit
apt-get install tesseract-ocr
```

## Run (Colab)
Open `ocr_project_colab.py` in Google Colab and run cells 1–14 in order.

## Dataset
Tobacco3482 — 3,482 real scanned corporate documents across 10 classes.
Download: https://www.kaggle.com/datasets/patrickaudriaz/tobacco3482jpg

## Frontend
```bash
streamlit run app.py
```
'''
with open("README.md", "w") as f:
    f.write(readme)

# Git push
cmds = [
    "git init",
    "git add ocr_project_colab.py app.py README.md ocr_project/outputs/ ocr_project/models/classifier.pkl",
    'git commit -m "Initial commit: OCR project"',
    f"git remote add origin https://{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git",
    "git branch -M main",
    "git push -u origin main"
]
for cmd in cmds:
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if result.returncode == 0:
        print(f"✅ {cmd[:40]}")
    else:
        print(f"❌ {cmd[:40]}: {result.stderr[:100]}")

print(f"\n🔗 GitHub URL: https://github.com/{GITHUB_USERNAME}/{REPO_NAME}")
"""